# Generated by Django 5.1.2 on 2024-11-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_is_active_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costume',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='costume_images/'),
        ),
    ]
