name: Python CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Set up Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run unit tests
      run: |
        pytest --maxfail=1 --disable-warnings --tb=short tests/unit

    - name: Run integration tests
      run: |
        pytest --maxfail=1 --disable-warnings --tb=short tests/integration
    
    # Static Type Checking using mypy
    - name: Run mypy for type checking
      run: |
        pip install mypy
        mypy --ignore-missing-imports .

    # Vulnerability checks
    - name: Security scan with bandit
      run: |
        pip install bandit
        bandit -r .

    - name: Check for dependency vulnerabilities
      run: |
        pip install pip-audit
        pip-audit

