# Generated by Django 4.2.16 on 2024-10-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wear_and_share", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_active",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
